package udream;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class Bsc_Courses_Panel extends javax.swing.JPanel {

    public void init() {
        overview.setLineWrap(true);
        overview.setWrapStyleWord(true);
        application_pre_req.setLineWrap(true);
        application_pre_req.setWrapStyleWord(true);
        ACT = false;
        SAT = false;
        ILETS = false;
        TOFEL = false;
        PTE = false;
        jLabel14.setVisible(false);
        Ilets_score.setVisible(false);
        jLabel15.setVisible(false);
        jLabel18.setVisible(false);
        jLabel28.setVisible(false);
        jLabel21.setVisible(false);
        jLabel22.setVisible(false);
        jLabel23.setVisible(false);
        jLabel26.setVisible(false);
        jLabel25.setVisible(false);
        jLabel27.setVisible(false);
        jLabel24.setVisible(false);
        jLabel11.setVisible(false);
        jLabel12.setVisible(false);
        sat_math_score.setVisible(false);
        sat_rw_score.setVisible(false);
        pte_score.setVisible(false);

        tofel_score.setVisible(false);
        act_score.setVisible(false);

    }
    boolean ACT, SAT, ILETS, TOFEL, PTE;
     public JFrame frame;
    public Bsc_Courses_Panel() {
        initComponents();
        init();
    }
    
        public Bsc_Courses_Panel(JFrame fr,String uni_name) {
        initComponents();
        init();
        frame=fr;
        university_name.setText(uni_name);
        System.out.println(uni_name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        course_name = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        overview = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        program_duration = new javax.swing.JTextField();
        credits = new javax.swing.JTextField();
        tution_fees = new javax.swing.JTextField();
        application_fees = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        application_pre_req = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        sat_math_score = new javax.swing.JTextField();
        sat_rw_score = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        pte_score = new javax.swing.JTextField();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jRadioButton7 = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        tofel_score = new javax.swing.JTextField();
        jRadioButton9 = new javax.swing.JRadioButton();
        jLabel20 = new javax.swing.JLabel();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jLabel21 = new javax.swing.JLabel();
        act_score = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        Ilets_score = new javax.swing.JComboBox<>();
        university_name = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane1.setViewportView(jTextArea2);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("Add SAT Score?");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Add Courses ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 19, 181, 33));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("University Name ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 83, 146, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Course Name");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 132, 84, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Overview");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 182, 63, -1));
        add(course_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 129, 585, -1));

        overview.setColumns(20);
        overview.setRows(5);
        jScrollPane2.setViewportView(overview);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 182, 585, 117));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Program Duration");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 338, 112, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Credits");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 395, 68, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Tuition Fees");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 443, 80, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Application Fees");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 496, 112, -1));
        add(program_duration, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 335, 585, -1));
        add(credits, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 392, 585, -1));
        add(tution_fees, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 440, 585, -1));
        add(application_fees, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 493, 585, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Application Pre Requisites");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 556, 160, -1));

        application_pre_req.setColumns(20);
        application_pre_req.setRows(5);
        jScrollPane3.setViewportView(application_pre_req);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 556, 585, 98));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Add SAT Score?");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 678, 99, -1));

        jRadioButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButton1.setText("Yes");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 678, 112, -1));

        jRadioButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButton2.setText("No");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 678, 50, -1));

        sat_math_score.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sat_math_scoreActionPerformed(evt);
            }
        });
        sat_math_score.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sat_math_scoreKeyReleased(evt);
            }
        });
        add(sat_math_score, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 710, 160, 40));

        sat_rw_score.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sat_rw_scoreActionPerformed(evt);
            }
        });
        sat_rw_score.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sat_rw_scoreKeyReleased(evt);
            }
        });
        add(sat_rw_score, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 700, 138, 40));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("MATH SCORE");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 720, 77, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("READ WRITE SCORE");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 720, 121, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Add ACT Score?");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 759, 111, -1));

        jRadioButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButton3.setText("Yes");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 760, -1, -1));

        jRadioButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButton4.setText("No");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 760, 60, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("SCORE");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 760, 53, -1));

        pte_score.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pte_scoreKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pte_scoreKeyReleased(evt);
            }
        });
        add(pte_score, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 870, 140, 20));

        jRadioButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButton5.setText("Yes");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });
        add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 790, 50, -1));

        jRadioButton6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButton6.setText("No");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });
        add(jRadioButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 790, 50, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("SCORE");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 790, 53, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("Add ILETS Score?");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 792, 111, -1));

        jRadioButton7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButton7.setText("Yes");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });
        add(jRadioButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 830, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setText("Add TOFEL Score?");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 828, 121, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setText("SCORE");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 830, 53, 22));

        tofel_score.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tofel_scoreActionPerformed(evt);
            }
        });
        tofel_score.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tofel_scoreKeyReleased(evt);
            }
        });
        add(tofel_score, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 830, 140, -1));

        jRadioButton9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButton9.setText("No");
        jRadioButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton9ActionPerformed(evt);
            }
        });
        add(jRadioButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 830, 51, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setText("Add PTE Score?");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 870, 100, -1));

        jRadioButton8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButton8.setText("Yes");
        jRadioButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton8ActionPerformed(evt);
            }
        });
        add(jRadioButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 870, 79, -1));

        jRadioButton10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButton10.setText("No");
        jRadioButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton10ActionPerformed(evt);
            }
        });
        add(jRadioButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 870, 50, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setText("SCORE");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 870, 53, -1));

        act_score.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                act_scoreActionPerformed(evt);
            }
        });
        act_score.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                act_scoreKeyReleased(evt);
            }
        });
        add(act_score, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 760, 140, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 930, 190, -1));

        jLabel22.setText("jLabel22");
        add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 790, 360, -1));

        jLabel23.setText("jLabel23");
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 720, 250, -1));

        jLabel24.setText("jLabel24");
        add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 760, 370, -1));

        jLabel25.setText("jLabel25");
        add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 720, 180, -1));

        jLabel26.setText("jLabel26");
        add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 830, 370, -1));

        jLabel27.setText("jLabel27");
        add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 870, 370, -1));

        Ilets_score.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "0.5", "1.0", "1.5", "2.0", "2.5", "3.0", "3.5", "4.0", "4.5", "5.0", "5.5", "6.0", "6.5", "7.0", "7.5", "8.0", "8.5", "9.0" }));
        add(Ilets_score, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 790, 140, -1));

        university_name.setEditable(false);
        university_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                university_nameActionPerformed(evt);
            }
        });
        add(university_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 590, -1));

        jLabel28.setText("jLabel28");
        add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 980, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        ACT = true;
        jLabel14.setVisible(true);
        act_score.setVisible(true);
        jRadioButton4.setSelected(false);

    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton10ActionPerformed
        jLabel21.setVisible(false);
        jLabel27.setVisible(false);
        pte_score.setVisible(false);
        pte_score.setText("");
        jRadioButton8.setSelected(false);
    }//GEN-LAST:event_jRadioButton10ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        jLabel15.setVisible(true);
        Ilets_score.setVisible(true);
        jRadioButton6.setSelected(false);
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        jLabel18.setVisible(true);
        tofel_score.setVisible(true);
        jRadioButton9.setSelected(false);
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void jRadioButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton8ActionPerformed
        jLabel21.setVisible(true);
        pte_score.setVisible(true);
        jRadioButton10.setSelected(false);
    }//GEN-LAST:event_jRadioButton8ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        jLabel11.setVisible(true);
        sat_math_score.setVisible(true);
        jLabel12.setVisible(true);
        sat_rw_score.setVisible(true);
        jRadioButton2.setSelected(false);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void sat_rw_scoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sat_rw_scoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sat_rw_scoreActionPerformed

    private void act_scoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_act_scoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_act_scoreActionPerformed
    String s = "";
    String ilets = "";
    private void sat_math_scoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sat_math_scoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sat_math_scoreActionPerformed
    String SAT_MATH = "";
    private void sat_math_scoreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sat_math_scoreKeyReleased
        char c = evt.getKeyChar();
        SAT_MATH += evt.getKeyChar();
        if (!Character.isDigit(c)) {
            jLabel23.setText("Enter Numeric value between 0 to 800");
            jLabel23.setVisible(true);
            sat_math_score.setText("");
            SAT_MATH = "";
        } else {
            double d = Double.parseDouble(SAT_MATH);
            System.out.println(d);
            if (d < 0 || d > 800) {
                jLabel23.setText("Enter Numeric value between 0 to 800");
                jLabel23.setVisible(true);
                sat_math_score.setText("");
                SAT_MATH = "";
            } else if (d >= 0 && d <= 800) {
                jLabel23.setVisible(false);
                jLabel23.setText("");

            }
        }
    }//GEN-LAST:event_sat_math_scoreKeyReleased

    private void tofel_scoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tofel_scoreActionPerformed

    }//GEN-LAST:event_tofel_scoreActionPerformed

    String tofel = "";
    private void tofel_scoreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tofel_scoreKeyReleased
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            jLabel26.setText("This field may only contain numeric characters from 0 to 120");
            jLabel26.setVisible(true);
            tofel_score.setText("");
            tofel = "";
        } else {
            tofel += evt.getKeyChar();
            System.out.println(tofel);
            double d = Double.parseDouble(tofel);
            if (d < 0 || d > 120) {
                tofel = "";
                jLabel26.setText("This field may only contain numeric characters from 0 to 120");
                jLabel26.setVisible(true);
                tofel_score.setText("");
            } else {
                jLabel26.setVisible(false);
                jLabel26.setText("");
            }

        }

    }//GEN-LAST:event_tofel_scoreKeyReleased
    String SAT_RW = "";
    private void sat_rw_scoreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sat_rw_scoreKeyReleased
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            jLabel25.setText("Enter Numeric value between 0 to 800");
            jLabel25.setVisible(true);
            sat_rw_score.setText("");
            SAT_RW = "";
        } else {
            SAT_RW += evt.getKeyChar();
            System.out.println(SAT_RW);
            double d = Double.parseDouble(SAT_RW);
            if (d < 0 || d > 800) {
                SAT_RW = "";
                jLabel25.setText("Enter Numeric value between 0 to 800");
                jLabel25.setVisible(true);
                sat_rw_score.setText("");
            } else {
                jLabel25.setVisible(false);
                jLabel25.setText("");
            }

        }
    }//GEN-LAST:event_sat_rw_scoreKeyReleased
    String act = "";
    private void act_scoreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_act_scoreKeyReleased
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            jLabel24.setText("This field may only contain numeric characters from 0 to 36");
            jLabel24.setVisible(true);
            act_score.setText("");
            act = "";
        } else {
            act += evt.getKeyChar();
            System.out.println(act);
            double d = Double.parseDouble(act);
            if (d < 0 || d > 36) {
                act = "";
                jLabel24.setText("This field may only contain numeric characters from 0 to 36");
                jLabel24.setVisible(true);
                act_score.setText("");
            } else {
                jLabel24.setVisible(false);
                jLabel24.setText("");
            }

        }
    }//GEN-LAST:event_act_scoreKeyReleased

    private void pte_scoreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pte_scoreKeyPressed

    }//GEN-LAST:event_pte_scoreKeyPressed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        jLabel14.setVisible(false);
        jLabel24.setVisible(false);
        act_score.setText("");
        act_score.setVisible(false);
        jRadioButton3.setSelected(false);

    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        jLabel15.setVisible(false);
        Ilets_score.setVisible(false);
        Ilets_score.setSelectedItem("");
        jLabel22.setVisible(false);
        jRadioButton5.setSelected(false);
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jRadioButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton9ActionPerformed
        jLabel18.setVisible(false);
        jLabel26.setVisible(false);
        tofel_score.setVisible(false);
        tofel_score.setText("");
        jRadioButton7.setSelected(false);
    }//GEN-LAST:event_jRadioButton9ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        jLabel11.setVisible(false);
        jLabel23.setVisible(false);
        jLabel25.setVisible(false);
        sat_math_score.setVisible(false);
        sat_math_score.setText("");
        jLabel12.setVisible(false);
        sat_rw_score.setVisible(false);
        sat_rw_score.setText("");
        jRadioButton1.setSelected(false);
    }//GEN-LAST:event_jRadioButton2ActionPerformed
    String pte = "";
    private void pte_scoreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pte_scoreKeyReleased
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            jLabel27.setText("This field may only contain numeric characters from 0 to 90");
            jLabel27.setVisible(true);
            pte_score.setText("");
            pte = "";
        } else {
            pte += evt.getKeyChar();
            System.out.println(pte);
            double d = Double.parseDouble(pte);
            if (d < 0 || d > 90) {
                pte = "";
                jLabel27.setText("This field may only contain numeric characters from 0 to 90");
                jLabel27.setVisible(true);
                pte_score.setText("");
            } else {
                jLabel27.setVisible(false);
                jLabel27.setText("");
            }

        }
    }//GEN-LAST:event_pte_scoreKeyReleased

    private void university_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_university_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_university_nameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project", "root", "rayhan19018");

            String sql = "insert into bsc_courses values(?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            System.out.print("yes");
            PreparedStatement st = con.prepareStatement(sql);

            //Converting String into int using Integer.parseInt()  
            if ((university_name.getText().isEmpty()) || (course_name.getText().isEmpty()) || (overview.getText().isEmpty()) || (program_duration.getText().isEmpty()) || (credits.getText().isEmpty()) || (tution_fees.getText().isEmpty()) || (application_fees.getText().isEmpty()) || (application_pre_req.getText().isEmpty())) {
                JOptionPane.showMessageDialog(null, "Some information is missing");
            } else {
                st.setString(1, university_name.getText());
                st.setString(2, course_name.getText());
                st.setString(3, overview.getText());
                int pd = 0, tf = 0, af = 0;
                double cr = 0, sm = 0, srw = 0, acts = 0, ils = 0, tfs = 0, pts = 0;
                if(program_duration.getText().isEmpty()==false)
                {
                    pd=Integer.parseInt(program_duration.getText());
                }
                 st.setInt(4, pd);
                 if(credits.getText().isEmpty()==false)
                 {
                     cr=Double.parseDouble(credits.getText());
                 }
                 st.setDouble(5, cr);
                 if(tution_fees.getText().isEmpty()==false)
                 {
                     tf=Integer.parseInt(tution_fees.getText());
                 }
                 st.setInt(6,tf);
                 if(application_fees.getText().isEmpty()==false)
                 {
                     af=Integer.parseInt(application_fees.getText());
                 }
                 st.setInt(7,af);
                 st.setString(8,application_pre_req.getText());
                 if(sat_math_score.getText().isEmpty()==false)
                 {
                     sm=Double.parseDouble(sat_math_score.getText());
                 }
                 st.setDouble(9,sm);
                 if(sat_rw_score.getText().isEmpty()==false)
                 {
                     srw=Double.parseDouble(sat_rw_score.getText());
                 }
                 st.setDouble(10, srw);
                 if(act_score.getText().isEmpty()==false)
                 {
                     acts=Double.parseDouble(act_score.getText());
                 }
                 st.setDouble(11, acts);
                 if(jRadioButton5.isSelected())
                 {
                     ils=Double.parseDouble(Ilets_score.getSelectedItem().toString());
                 }
                st.setDouble(12, ils);
                if(tofel_score.getText().isEmpty()==false)
                {
                    tfs=Double.parseDouble(tofel_score.getText());
                }
                st.setDouble(13, tfs);
                if(pte_score.getText().isEmpty()==false)
                {
                    pts=Double.parseDouble(pte_score.getText());
                }
                 st.setDouble(14, pts);
                   st.executeUpdate();
            JOptionPane.showMessageDialog(null,"Insertion Successful");
             Available_courses_for_BSc_Of_university.showcourses();
            frame.dispose();
            }

            //double le=Double.parseDouble(LivingExpenses.getText());
            // st.setDouble(5,le);
            //  int i=Integer.parseInt(ApplicationFee.getText()); 
            // JOptionPane.showMessageDialog(null,"Insertion Successful");
        } catch (Exception e) {
 JOptionPane.showMessageDialog(null,"Insertion Is Not Successful");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Ilets_score;
    private javax.swing.JTextField act_score;
    private javax.swing.JTextField application_fees;
    private javax.swing.JTextArea application_pre_req;
    private javax.swing.JTextField course_name;
    private javax.swing.JTextField credits;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea overview;
    private javax.swing.JTextField program_duration;
    private javax.swing.JTextField pte_score;
    private javax.swing.JTextField sat_math_score;
    private javax.swing.JTextField sat_rw_score;
    private javax.swing.JTextField tofel_score;
    private javax.swing.JTextField tution_fees;
    private javax.swing.JTextField university_name;
    // End of variables declaration//GEN-END:variables
}
