/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UDream;

import java.awt.Image;
import javax.swing.JFrame;
import scrollbar.ScrollBarCustom;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import scrollclspackage.university_pagecls;

public class CoursePage extends javax.swing.JPanel {
    
JFrame cls;
String Uni_name;
String C_name;
    public CoursePage(JFrame frame,String s,String s1) {
        initComponents();
        cls = frame;
        Uni_name=s;
        C_name = s1;
    OverviewScroll.setVerticalScrollBar(new ScrollBarCustom());
    RequisiteScroll.setVerticalScrollBar(new ScrollBarCustom());
    info();
    }
void info(){
    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project", "root", "rayhan19018");
        PreparedStatement st = con.prepareStatement("select * from bsc_courses where University_Name = ? AND  Course_Name = ?");
        st.setString(1,Uni_name);
        st.setString(2,C_name);
        ResultSet rs = st.executeQuery();
        if(rs.next()){
            Course.setText(rs.getString("Course_Name"));
            University.setText(rs.getString("University_Name"));
            PreparedStatement st1= con.prepareStatement("select * from university_info where University_Name = ?");
            st1.setString(1,Uni_name);
            ResultSet rs1 = st1.executeQuery();
            if(rs1.next()){
             byte[] img = rs1.getBytes("Icon");
               ImageIcon image = new ImageIcon(img);
               Image im= image.getImage();
               Image myimg = im.getScaledInstance(110,110,Image.SCALE_SMOOTH);
               ImageIcon ni = new ImageIcon(myimg);
               imageAvatar1.setImage(ni); }
            OverviewTextarea.setText(rs.getString("Overview"));
            Duration.setText(rs.getString("Program_Duration"));
            Course_name.setText(rs.getString("Course_Name"));
            Credit.setText(Double.toString(rs.getDouble("Credits")));
            Semester.setText("8");
            Annual_Tution.setText("$" + Integer. toString(rs.getInt("Tution_Fees")));
            Full_Tution.setText("$" + Integer. toString((rs.getInt("Tution_Fees")*4)));
            App_fee.setText("$" + Integer. toString(rs.getInt("Application_Fees")));
            RequisiteArea.setText(rs.getString("Application_Pre_Requisites"));
            if(rs.getDouble("SAT_MATH")== 0){
                jLabel34.setVisible(false);
            }
            else
                Satmath.setText(Double.toString(rs.getDouble("SAT_Math")));
            if(rs.getDouble("SAT_READ_WRITE")== 0){
                sat.setVisible(false);
            }
            else
                Sat.setText(Double.toString(rs.getDouble("SAT_READ_WRITE")));
            if(rs.getDouble("ILETS")== 0){
                jLabel35.setVisible(false);
            }
            else
                IELTS.setText(Double.toString(rs.getDouble("ILETS")));
            if(rs.getDouble("TOFEL")== 0){
                jLabel38.setVisible(false);
            }
            else
               TOFEL.setText(Double.toString(rs.getDouble("TOFEL")));
            if(rs.getDouble("ACT")== 0){
                jLabel36.setVisible(false);
            }
            else
                ACT.setText(Double.toString(rs.getDouble("ACT")));
            if(rs.getDouble("PTE")== 0){
                jLabel37.setVisible(false);
            }
            else
                PTE.setText(Double.toString(rs.getDouble("PTE")));
        }
    } catch (SQLException | ClassNotFoundException ex) {
        Logger.getLogger(CoursePage.class.getName()).log(Level.SEVERE, null, ex);
    }}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Course = new javax.swing.JLabel();
        University = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        imageAvatar1 = new main.ImageAvatar();
        panelRound1 = new test.PanelRound();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        OverviewScroll = new javax.swing.JScrollPane();
        OverviewTextarea = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        panelRound2 = new test.PanelRound();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Duration = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Course_name = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Credit = new javax.swing.JTextField();
        Semester = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        panelRound3 = new test.PanelRound();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        Full_Tution = new javax.swing.JTextField();
        Annual_Tution = new javax.swing.JTextField();
        panelRound4 = new test.PanelRound();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        App_fee = new javax.swing.JTextField();
        panelRound5 = new test.PanelRound();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        RequisiteScroll = new javax.swing.JScrollPane();
        RequisiteArea = new javax.swing.JTextArea();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        sat = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        Satmath = new javax.swing.JTextField();
        IELTS = new javax.swing.JTextField();
        ACT = new javax.swing.JTextField();
        Sat = new javax.swing.JTextField();
        TOFEL = new javax.swing.JTextField();
        PTE = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Course.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jPanel1.add(Course, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 720, 66));

        University.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        University.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(University, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 73, 720, 27));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 0));
        jLabel3.setText("View University >>");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 107, 159, -1));
        jPanel1.add(imageAvatar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 135, 135));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 41, 940, 170));

        panelRound1.setBackground(new java.awt.Color(255, 255, 255));
        panelRound1.setRoundBottomLeft(100);
        panelRound1.setRoundTopRight(100);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        jLabel4.setText("Overview");
        panelRound1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 131, 32));

        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("_____________________________________________________________________________________________________________________________________");
        panelRound1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 680, 30));

        OverviewScroll.setBorder(null);

        OverviewTextarea.setEditable(false);
        OverviewTextarea.setColumns(20);
        OverviewTextarea.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        OverviewTextarea.setLineWrap(true);
        OverviewTextarea.setRows(5);
        OverviewTextarea.setWrapStyleWord(true);
        OverviewTextarea.setBorder(null);
        OverviewScroll.setViewportView(OverviewTextarea);

        panelRound1.add(OverviewScroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 690, 160));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 102, 0));
        jLabel8.setText("|");
        panelRound1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 10, 30));

        add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 750, 240));

        panelRound2.setBackground(new java.awt.Color(255, 255, 255));
        panelRound2.setRoundBottomLeft(100);
        panelRound2.setRoundTopRight(100);
        panelRound2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 102, 0));
        jLabel6.setText("|");
        panelRound2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 10, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel7.setText("Course Highlights");
        panelRound2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 310, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Program Duration");
        panelRound2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 170, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/duration.PNG"))); // NOI18N
        jLabel10.setText("jLabel10");
        panelRound2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 40, 30));

        Duration.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Duration.setBorder(null);
        Duration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DurationActionPerformed(evt);
            }
        });
        panelRound2.add(Duration, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 180, 30));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Course Name");
        panelRound2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 130, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/course name.PNG"))); // NOI18N
        panelRound2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 40, 30));

        Course_name.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Course_name.setBorder(null);
        Course_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Course_nameActionPerformed(evt);
            }
        });
        panelRound2.add(Course_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 200, 30));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Course Credit");
        panelRound2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 130, 30));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/course credit.PNG"))); // NOI18N
        jLabel14.setText("jLabel14");
        panelRound2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 40, 30));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Number of  Semester");
        panelRound2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 180, 30));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/semester number.PNG"))); // NOI18N
        panelRound2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, -1, 30));

        Credit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Credit.setBorder(null);
        panelRound2.add(Credit, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 190, 30));

        Semester.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Semester.setBorder(null);
        panelRound2.add(Semester, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 190, 30));

        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setText("_______________________________________________________________________________________________________________________________________");
        panelRound2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 680, -1));

        add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 530, 750, 310));

        panelRound3.setBackground(new java.awt.Color(255, 255, 255));
        panelRound3.setFocusable(false);
        panelRound3.setRoundBottomLeft(100);
        panelRound3.setRoundTopRight(100);
        panelRound3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setText("Tution Fee");
        panelRound3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, -1));

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 102, 0));
        jLabel20.setText("|");
        panelRound3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 40));

        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("_______________________________________________________________________________________________________________________________________");
        panelRound3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 680, 20));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 102, 102));
        jLabel21.setText("Full Course Tution Fee (48 Month)");
        panelRound3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 300, 30));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 102, 102));
        jLabel22.setText("Annual Tution Fee");
        panelRound3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 56, 150, 30));

        Full_Tution.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Full_Tution.setForeground(new java.awt.Color(0, 204, 0));
        Full_Tution.setBorder(null);
        panelRound3.add(Full_Tution, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 150, 30));

        Annual_Tution.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Annual_Tution.setForeground(new java.awt.Color(0, 204, 0));
        Annual_Tution.setBorder(null);
        Annual_Tution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Annual_TutionActionPerformed(evt);
            }
        });
        panelRound3.add(Annual_Tution, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 150, 30));

        add(panelRound3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 880, 750, 170));

        panelRound4.setBackground(new java.awt.Color(255, 255, 255));
        panelRound4.setRoundBottomLeft(100);
        panelRound4.setRoundTopRight(100);
        panelRound4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 102, 0));
        jLabel23.setText("|");
        panelRound4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 40));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel24.setText("Admission");
        panelRound4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 140, 40));

        jLabel25.setForeground(new java.awt.Color(102, 102, 102));
        jLabel25.setText("_______________________________________________________________________________________________________________________________________");
        panelRound4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 680, 20));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(102, 102, 102));
        jLabel26.setText("Application Fee");
        panelRound4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 120, 30));

        App_fee.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        App_fee.setForeground(new java.awt.Color(0, 204, 0));
        App_fee.setBorder(null);
        panelRound4.add(App_fee, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 170, 30));

        add(panelRound4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 1090, 750, 150));

        panelRound5.setBackground(new java.awt.Color(255, 255, 255));
        panelRound5.setRoundBottomLeft(100);
        panelRound5.setRoundTopRight(100);
        panelRound5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel27.setText("Pre-Requisities");
        panelRound5.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 250, 40));

        jLabel28.setBackground(new java.awt.Color(255, 255, 255));
        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 102, 0));
        jLabel28.setText("|");
        panelRound5.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 40));

        jLabel29.setForeground(new java.awt.Color(102, 102, 102));
        jLabel29.setText("__________________________________________________________________________________________________________________________________________");
        panelRound5.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 730, 20));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(102, 102, 102));
        jLabel30.setText("Test Score Requirements");
        panelRound5.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 220, 30));

        RequisiteScroll.setBackground(new java.awt.Color(255, 255, 255));
        RequisiteScroll.setBorder(null);

        RequisiteArea.setColumns(20);
        RequisiteArea.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RequisiteArea.setLineWrap(true);
        RequisiteArea.setRows(6);
        RequisiteArea.setWrapStyleWord(true);
        RequisiteArea.setBorder(null);
        RequisiteScroll.setViewportView(RequisiteArea);

        panelRound5.add(RequisiteScroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 670, 130));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(102, 102, 102));
        jLabel31.setText("Application Pre-Requisities");
        panelRound5.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 220, 30));

        jLabel32.setForeground(new java.awt.Color(102, 102, 102));
        jLabel32.setText("_______________________________________________________________________________________________________________________________________");
        panelRound5.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 680, 20));

        sat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sat.setForeground(new java.awt.Color(153, 153, 153));
        sat.setText("SAT Read/Write ");
        panelRound5.add(sat, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 120, -1));

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(153, 153, 153));
        jLabel34.setText("SAT Math");
        panelRound5.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 90, -1));

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(153, 153, 153));
        jLabel35.setText("IELTS");
        panelRound5.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 90, -1));

        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(153, 153, 153));
        jLabel36.setText("ACT");
        panelRound5.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 90, -1));

        jLabel37.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(153, 153, 153));
        jLabel37.setText("PTE");
        panelRound5.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 90, -1));

        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(153, 153, 153));
        jLabel38.setText("TOFEL");
        panelRound5.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 90, -1));

        Satmath.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Satmath.setBorder(null);
        Satmath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SatmathActionPerformed(evt);
            }
        });
        panelRound5.add(Satmath, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 70, -1));

        IELTS.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        IELTS.setBorder(null);
        panelRound5.add(IELTS, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 70, -1));

        ACT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ACT.setBorder(null);
        ACT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACTActionPerformed(evt);
            }
        });
        panelRound5.add(ACT, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 70, -1));

        Sat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Sat.setBorder(null);
        panelRound5.add(Sat, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 70, -1));

        TOFEL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TOFEL.setBorder(null);
        panelRound5.add(TOFEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, 70, -1));

        PTE.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PTE.setBorder(null);
        panelRound5.add(PTE, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 70, -1));

        add(panelRound5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 1280, 750, 370));
    }// </editor-fold>//GEN-END:initComponents

    private void DurationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DurationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DurationActionPerformed

    private void Course_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Course_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Course_nameActionPerformed

    private void Annual_TutionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Annual_TutionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Annual_TutionActionPerformed

    private void SatmathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SatmathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SatmathActionPerformed

    private void ACTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ACTActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
       university_pagecls ob = new university_pagecls(Uni_name);
       ob.setVisible(true);
       cls.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ACT;
    private javax.swing.JTextField Annual_Tution;
    private javax.swing.JTextField App_fee;
    private javax.swing.JLabel Course;
    private javax.swing.JTextField Course_name;
    private javax.swing.JTextField Credit;
    private javax.swing.JTextField Duration;
    private javax.swing.JTextField Full_Tution;
    private javax.swing.JTextField IELTS;
    private javax.swing.JScrollPane OverviewScroll;
    private javax.swing.JTextArea OverviewTextarea;
    private javax.swing.JTextField PTE;
    private javax.swing.JTextArea RequisiteArea;
    private javax.swing.JScrollPane RequisiteScroll;
    private javax.swing.JTextField Sat;
    private javax.swing.JTextField Satmath;
    private javax.swing.JTextField Semester;
    private javax.swing.JTextField TOFEL;
    private javax.swing.JLabel University;
    private main.ImageAvatar imageAvatar1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private test.PanelRound panelRound1;
    private test.PanelRound panelRound2;
    private test.PanelRound panelRound3;
    private test.PanelRound panelRound4;
    private test.PanelRound panelRound5;
    private javax.swing.JLabel sat;
    // End of variables declaration//GEN-END:variables
}
