
package UDream;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Image;
import java.awt.Rectangle;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollBar;
import javax.swing.JScrollPane;
import scrollbar.ScrollBarCustom;
import test.PanelRound;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
public class NewJPanel extends javax.swing.JPanel {

   JFrame cls;
   String str;
    public NewJPanel(JFrame frame,String s) {
        initComponents();
        str = s;
        cls = frame;
        AboutScroll.setVerticalScrollBar(new ScrollBarCustom());
        ContactScroll.setVerticalScrollBar(new ScrollBarCustom());
        CourseScroll.setVerticalScrollBar(new ScrollBarCustom());
        info(); 
    }
     DefaultListModel model = new DefaultListModel();
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UniName = new javax.swing.JPanel();
        Name = new javax.swing.JLabel();
        Country = new javax.swing.JLabel();
        Established = new javax.swing.JLabel();
        imageAvatar1 = new main.ImageAvatar();
        ContactPanel = new test.PanelRound();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Fbfield = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        ContactScroll = new javax.swing.JScrollPane();
        Addressfield = new javax.swing.JTextArea();
        jLabel24 = new javax.swing.JLabel();
        Emailfield = new javax.swing.JTextField();
        Website = new javax.swing.JLabel();
        CostPanel = new test.PanelRound();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        TutionfeeField = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        BachelorExpenses = new javax.swing.JTextField();
        OnCampusExpenses = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        AboutPanel = new test.PanelRound();
        jLabel9 = new javax.swing.JLabel();
        AboutScroll = new javax.swing.JScrollPane();
        AboutText = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        RankingPanel = new test.PanelRound();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Rankingfield = new javax.swing.JTextArea();
        AdmissionPanel = new test.PanelRound();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Applicationfee = new javax.swing.JTextField();
        CoursePanel = new test.PanelRound();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        CourseScroll = new javax.swing.JScrollPane();
        CourseList = new javax.swing.JList<>();
        PhotoPanel = new test.PanelRound();
        jLabel13 = new javax.swing.JLabel();
        Photo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UniName.setBackground(new java.awt.Color(255, 255, 255));
        UniName.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Name.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        UniName.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 890, 60));

        Country.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Country.setForeground(new java.awt.Color(102, 102, 102));
        UniName.add(Country, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 76, 140, 30));

        Established.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Established.setForeground(new java.awt.Color(102, 102, 102));
        UniName.add(Established, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 80, 230, 20));

        imageAvatar1.setBorderSize(1);
        UniName.add(imageAvatar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 120));

        add(UniName, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 44, 1080, 120));

        ContactPanel.setBackground(new java.awt.Color(255, 255, 255));
        ContactPanel.setRoundBottomRight(100);
        ContactPanel.setRoundTopLeft(100);
        ContactPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Contact Info");
        ContactPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 13, 180, 27));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("Facebook");
        ContactPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 120, 26));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 255));
        jLabel8.setText("Website");
        ContactPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 200, 30));

        Fbfield.setEditable(false);
        Fbfield.setBackground(new java.awt.Color(255, 255, 255));
        Fbfield.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Fbfield.setForeground(new java.awt.Color(0, 153, 0));
        Fbfield.setBorder(null);
        ContactPanel.add(Fbfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 730, 40));

        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("__________________________________________________________________________________________________________________________________________________________");
        ContactPanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 26, 960, 20));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 255));
        jLabel12.setText("Email Address");
        ContactPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 156, 26));

        ContactScroll.setBorder(null);

        Addressfield.setEditable(false);
        Addressfield.setColumns(20);
        Addressfield.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Addressfield.setRows(2);
        Addressfield.setBorder(null);
        ContactScroll.setViewportView(Addressfield);

        ContactPanel.add(ContactScroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 780, 50));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 51, 255));
        jLabel24.setText("University Address");
        ContactPanel.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 200, 30));

        Emailfield.setEditable(false);
        Emailfield.setBackground(new java.awt.Color(255, 255, 255));
        Emailfield.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Emailfield.setForeground(new java.awt.Color(0, 153, 0));
        Emailfield.setBorder(null);
        Emailfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailfieldActionPerformed(evt);
            }
        });
        ContactPanel.add(Emailfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 780, 40));

        Website.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Website.setForeground(new java.awt.Color(0, 153, 0));
        Website.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                WebsiteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                WebsiteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                WebsiteMouseExited(evt);
            }
        });
        ContactPanel.add(Website, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 86, 310, 30));

        add(ContactPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 1310, 810, 400));

        CostPanel.setBackground(new java.awt.Color(255, 255, 255));
        CostPanel.setRoundBottomRight(100);
        CostPanel.setRoundTopLeft(100);
        CostPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel18.setText("Cost");
        CostPanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 13, 74, 27));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 255));
        jLabel19.setText("Living Expence:");
        CostPanel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 156, 26));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 51, 255));
        jLabel20.setText("Avarage Tution Fee");
        CostPanel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 200, 30));

        TutionfeeField.setEditable(false);
        TutionfeeField.setBackground(new java.awt.Color(255, 255, 255));
        TutionfeeField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TutionfeeField.setBorder(null);
        CostPanel.add(TutionfeeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 750, 40));

        jLabel21.setForeground(new java.awt.Color(102, 102, 102));
        jLabel21.setText("Avarage Living Expenses (Bachelors)");
        CostPanel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 220, 30));

        jLabel22.setForeground(new java.awt.Color(102, 102, 102));
        jLabel22.setText("Avarage On Campus Living Expense");
        CostPanel.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 166, 220, 30));

        BachelorExpenses.setEditable(false);
        BachelorExpenses.setBackground(new java.awt.Color(255, 255, 255));
        BachelorExpenses.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BachelorExpenses.setForeground(new java.awt.Color(0, 153, 0));
        BachelorExpenses.setBorder(null);
        BachelorExpenses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BachelorExpensesActionPerformed(evt);
            }
        });
        CostPanel.add(BachelorExpenses, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 202, 290, 40));

        OnCampusExpenses.setEditable(false);
        OnCampusExpenses.setBackground(new java.awt.Color(255, 255, 255));
        OnCampusExpenses.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        OnCampusExpenses.setForeground(new java.awt.Color(0, 153, 0));
        OnCampusExpenses.setBorder(null);
        CostPanel.add(OnCampusExpenses, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 310, 40));

        jLabel23.setForeground(new java.awt.Color(102, 102, 102));
        jLabel23.setText("__________________________________________________________________________________________________________________________________________________________");
        CostPanel.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 26, 960, 20));

        add(CostPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 800, 252));

        AboutPanel.setBackground(new java.awt.Color(255, 255, 255));
        AboutPanel.setRoundBottomRight(50);
        AboutPanel.setRoundTopLeft(100);
        AboutPanel.setRoundTopRight(50);
        AboutPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("About");
        AboutPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 13, 115, 28));

        AboutScroll.setBackground(new java.awt.Color(255, 255, 255));
        AboutScroll.setBorder(null);

        AboutText.setEditable(false);
        AboutText.setColumns(20);
        AboutText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AboutText.setLineWrap(true);
        AboutText.setRows(2);
        AboutText.setWrapStyleWord(true);
        AboutText.setBorder(null);
        AboutScroll.setViewportView(AboutText);

        AboutPanel.add(AboutScroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 780, 90));

        jLabel14.setForeground(new java.awt.Color(153, 153, 153));
        jLabel14.setText("_____________________________________________________________________________________________________________________________________________________________");
        AboutPanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 26, 960, 20));

        add(AboutPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 800, 160));

        RankingPanel.setBackground(new java.awt.Color(255, 255, 255));
        RankingPanel.setRoundBottomRight(50);
        RankingPanel.setRoundTopLeft(100);
        RankingPanel.setRoundTopRight(50);
        RankingPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Ranking");
        RankingPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 13, 115, 28));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        Rankingfield.setEditable(false);
        Rankingfield.setColumns(20);
        Rankingfield.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Rankingfield.setLineWrap(true);
        Rankingfield.setRows(1);
        Rankingfield.setWrapStyleWord(true);
        Rankingfield.setBorder(null);
        jScrollPane1.setViewportView(Rankingfield);

        RankingPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 780, 40));

        add(RankingPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 660, 800, 100));

        AdmissionPanel.setBackground(new java.awt.Color(255, 255, 255));
        AdmissionPanel.setRoundBottomRight(100);
        AdmissionPanel.setRoundTopLeft(100);
        AdmissionPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("Admission");
        AdmissionPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 13, 130, 27));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 255));
        jLabel11.setText("Application Fee");
        AdmissionPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 156, 26));

        Applicationfee.setEditable(false);
        Applicationfee.setBackground(new java.awt.Color(255, 255, 255));
        Applicationfee.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Applicationfee.setForeground(new java.awt.Color(0, 153, 0));
        Applicationfee.setBorder(null);
        AdmissionPanel.add(Applicationfee, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 730, 40));

        add(AdmissionPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 800, 800, -1));

        CoursePanel.setBackground(new java.awt.Color(255, 255, 255));
        CoursePanel.setRoundBottomLeft(50);
        CoursePanel.setRoundBottomRight(50);
        CoursePanel.setRoundTopLeft(50);
        CoursePanel.setRoundTopRight(50);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel16.setText("Courses");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("Click from the list to show detaild infromation about the courses");

        CourseScroll.setBorder(null);

        CourseList.setBackground(new java.awt.Color(255, 204, 204));
        CourseList.setFixedCellHeight(30);
        CourseList.setSelectionBackground(new java.awt.Color(255, 0, 0));
        CourseList.setVisibleRowCount(-1);
        CourseList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CourseListMouseClicked(evt);
            }
        });
        CourseList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                CourseListValueChanged(evt);
            }
        });
        CourseScroll.setViewportView(CourseList);

        javax.swing.GroupLayout CoursePanelLayout = new javax.swing.GroupLayout(CoursePanel);
        CoursePanel.setLayout(CoursePanelLayout);
        CoursePanelLayout.setHorizontalGroup(
            CoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CoursePanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(CoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CourseScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 775, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CoursePanelLayout.setVerticalGroup(
            CoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CoursePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CourseScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(CoursePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 980, 800, 280));

        PhotoPanel.setBackground(new java.awt.Color(255, 255, 255));
        PhotoPanel.setRoundBottomRight(100);
        PhotoPanel.setRoundTopLeft(100);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setText("Photo");

        Photo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout PhotoPanelLayout = new javax.swing.GroupLayout(PhotoPanel);
        PhotoPanel.setLayout(PhotoPanelLayout);
        PhotoPanelLayout.setHorizontalGroup(
            PhotoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PhotoPanelLayout.createSequentialGroup()
                .addGroup(PhotoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PhotoPanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PhotoPanelLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(Photo, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        PhotoPanelLayout.setVerticalGroup(
            PhotoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PhotoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Photo, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addGap(7, 7, 7))
        );

        add(PhotoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 1750, 810, 350));
    }// </editor-fold>//GEN-END:initComponents
 void info(){
       try {
           Class.forName("com.mysql.cj.jdbc.Driver");
           Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project", "root", "rayhan19018");
           PreparedStatement st = con.prepareStatement("select * from university_info where University_Name = ?");
           st.setString(1,str);
           ResultSet rs = st.executeQuery();
           if(rs.next()){
               Name.setText(rs.getString("University_Name"));
               byte[] img = rs.getBytes("Icon");
               ImageIcon image = new ImageIcon(img);
               Image im= image.getImage();
               Image myimg = im.getScaledInstance(110,110,Image.SCALE_SMOOTH);
               ImageIcon ni = new ImageIcon(myimg);
           //    Icon.setIcon(ni);
               imageAvatar1.setImage(ni); 
           }
           Country.setText(rs.getString("Country"));
           Established.setText("Established in " + rs.getString("Established Year"));
           AboutText.setText(rs.getString("About"));
           TutionfeeField.setText("$" + (rs.getString("Cost")));
           BachelorExpenses.setText("$" + Double. toString(rs.getDouble("Living Expenses(Bachelor)")));
           OnCampusExpenses.setText("$" + Double. toString(rs.getDouble("Living Expenses(On Campus)")));
           Rankingfield.setText("#"+ Integer.toString(rs.getInt("Ranking")));
           Applicationfee.setText("$"+ Integer.toString(rs.getInt("Application Fee")));
            byte[] img = rs.getBytes("Picture");
               ImageIcon image = new ImageIcon(img);
               Image im= image.getImage();
               Image myimg = im.getScaledInstance(516,280,Image.SCALE_SMOOTH);
               ImageIcon ni = new ImageIcon(myimg);
               Photo.setIcon(ni);
           Website.setText(rs.getString("Website"));
           Addressfield.setText(rs.getString("University Address"));
           Emailfield.setText(rs.getString("Email"));
           Fbfield.setText(rs.getString("Facebook ID"));
       PreparedStatement st1 = con.prepareStatement("select * from bsc_courses where University_Name = ?");   
        st1.setString(1,str);
        ResultSet rs1 = st1.executeQuery();
        while(rs1.next()){
            model.addElement(rs1.getString("Course_Name"));
        }
        CourseList.setModel(model);
        
     int a =  CourseList.getModel().getSize();
     if(a<6){
         if(a==3)
             CourseList.setFixedCellHeight(53);
         if(a==4)
            CourseList.setFixedCellHeight(42);
         if(a==5)
             CourseList.setFixedCellHeight(34);
     }
     System.out.println(a);
       } catch (SQLException ex) {
           Logger.getLogger(NewJPanel.class.getName()).log(Level.SEVERE, null, ex);
       } catch (ClassNotFoundException ex) {
           Logger.getLogger(NewJPanel.class.getName()).log(Level.SEVERE, null, ex);
       }
           
    }
    private void EmailfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailfieldActionPerformed

    private void WebsiteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WebsiteMouseClicked
        try {
            Website.setForeground(Color.BLUE.darker());
            Desktop.getDesktop().browse(new URI("www."+Website.getText()));
        } catch (URISyntaxException ex) {
            Logger.getLogger(NewJPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(NewJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_WebsiteMouseClicked

    private void WebsiteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WebsiteMouseEntered
        Website.setForeground(Color.RED.darker());
    }//GEN-LAST:event_WebsiteMouseEntered

    private void WebsiteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WebsiteMouseExited
        Website.setForeground(Color.GREEN.darker());
    }//GEN-LAST:event_WebsiteMouseExited

    private void BachelorExpensesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BachelorExpensesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BachelorExpensesActionPerformed

    private void CourseListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CourseListMouseClicked
        /*  String s = CourseList.getSelectedValue();
        Course_page ob =new Course_page(s);
        ob.setVisible(true);
        cls.dispose();*/
    }//GEN-LAST:event_CourseListMouseClicked

    private void CourseListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_CourseListValueChanged

    }//GEN-LAST:event_CourseListValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private test.PanelRound AboutPanel;
    private javax.swing.JScrollPane AboutScroll;
    private javax.swing.JTextArea AboutText;
    private javax.swing.JTextArea Addressfield;
    private test.PanelRound AdmissionPanel;
    private javax.swing.JTextField Applicationfee;
    private javax.swing.JTextField BachelorExpenses;
    private test.PanelRound ContactPanel;
    private javax.swing.JScrollPane ContactScroll;
    private test.PanelRound CostPanel;
    private javax.swing.JLabel Country;
    private javax.swing.JList<String> CourseList;
    private test.PanelRound CoursePanel;
    private javax.swing.JScrollPane CourseScroll;
    private javax.swing.JTextField Emailfield;
    private javax.swing.JLabel Established;
    private javax.swing.JTextField Fbfield;
    private javax.swing.JLabel Name;
    private javax.swing.JTextField OnCampusExpenses;
    private javax.swing.JLabel Photo;
    private test.PanelRound PhotoPanel;
    private test.PanelRound RankingPanel;
    private javax.swing.JTextArea Rankingfield;
    private javax.swing.JTextField TutionfeeField;
    private javax.swing.JPanel UniName;
    private javax.swing.JLabel Website;
    private main.ImageAvatar imageAvatar1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
