/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UDream;

import javax.swing.DefaultListModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.*;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import scrollclspackage.UpdateRankingCls;
/**
 *
 * @author RAYHAN
 */
public class Update_Ranking extends javax.swing.JPanel {

JFrame cls;
    public Update_Ranking(JFrame frame) {
        initComponents();
         cls= frame;
         scroll.setVisible(false);
      }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scroll = new javax.swing.JScrollPane();
        list = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        fac_ratio2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        curr_rank = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        teach1 = new javax.swing.JTextField();
        employ1 = new javax.swing.JTextField();
        stu_ratio1 = new javax.swing.JTextField();
        stu_fac1 = new javax.swing.JTextField();
        academic1 = new javax.swing.JTextField();
        citation1 = new javax.swing.JTextField();
        fac_ratio1 = new javax.swing.JTextField();
        teach2 = new javax.swing.JTextField();
        employ2 = new javax.swing.JTextField();
        stu_ratio2 = new javax.swing.JTextField();
        stu_fac2 = new javax.swing.JTextField();
        academic2 = new javax.swing.JTextField();
        citation2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        overall1 = new javax.swing.JTextField();
        overall2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scroll.setPreferredSize(new java.awt.Dimension(32, 200));

        list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listMouseClicked(evt);
            }
        });
        scroll.setViewportView(list);

        add(scroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 173, 370, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Update University Ranking");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 68, -1, 38));

        fac_ratio2.setMinimumSize(new java.awt.Dimension(7, 33));
        fac_ratio2.setPreferredSize(new java.awt.Dimension(50, 33));
        fac_ratio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fac_ratio2ActionPerformed(evt);
            }
        });
        add(fac_ratio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 710, 70, 40));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("University Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 143, 150, 26));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Current Ranking");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 223, 150, -1));

        name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameFocusLost(evt);
            }
        });
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameKeyReleased(evt);
            }
        });
        add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 143, 370, 33));

        curr_rank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                curr_rankActionPerformed(evt);
            }
        });
        add(curr_rank, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 90, 31));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Indicator Name");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 204));
        jLabel9.setText("3. Employer Reputaion");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 600, -1, 20));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 204));
        jLabel10.setText("1. Teaching");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 204));
        jLabel11.setText("2. Citation Per Year");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 204));
        jLabel12.setText("4. International Student Ratio");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 660, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 204));
        jLabel13.setText("5. International Faculty Ratio");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 720, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 204));
        jLabel14.setText("6. Student Faculty Ratio");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 780, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 204));
        jLabel15.setText("7. Academic Reputaion");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 840, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel5.setText(" Ranking Indicator");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("New Value");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, -1, -1));

        teach1.setMinimumSize(new java.awt.Dimension(7, 33));
        teach1.setPreferredSize(new java.awt.Dimension(50, 33));
        teach1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teach1ActionPerformed(evt);
            }
        });
        add(teach1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 470, 70, 40));

        employ1.setMinimumSize(new java.awt.Dimension(7, 33));
        employ1.setPreferredSize(new java.awt.Dimension(50, 33));
        employ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employ1ActionPerformed(evt);
            }
        });
        add(employ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 590, 70, 40));

        stu_ratio1.setMinimumSize(new java.awt.Dimension(7, 33));
        stu_ratio1.setPreferredSize(new java.awt.Dimension(50, 33));
        stu_ratio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stu_ratio1ActionPerformed(evt);
            }
        });
        add(stu_ratio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 650, 70, 40));

        stu_fac1.setMinimumSize(new java.awt.Dimension(7, 33));
        stu_fac1.setPreferredSize(new java.awt.Dimension(50, 33));
        add(stu_fac1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 770, 70, 40));

        academic1.setMinimumSize(new java.awt.Dimension(7, 33));
        academic1.setPreferredSize(new java.awt.Dimension(50, 33));
        academic1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                academic1ActionPerformed(evt);
            }
        });
        add(academic1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 830, 70, 40));

        citation1.setMinimumSize(new java.awt.Dimension(7, 33));
        citation1.setPreferredSize(new java.awt.Dimension(50, 33));
        citation1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                citation1ActionPerformed(evt);
            }
        });
        add(citation1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 530, 70, 40));

        fac_ratio1.setMinimumSize(new java.awt.Dimension(7, 33));
        fac_ratio1.setPreferredSize(new java.awt.Dimension(50, 33));
        add(fac_ratio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 710, 70, 40));

        teach2.setMinimumSize(new java.awt.Dimension(7, 33));
        teach2.setPreferredSize(new java.awt.Dimension(50, 33));
        teach2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teach2ActionPerformed(evt);
            }
        });
        add(teach2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 470, 70, 40));

        employ2.setMinimumSize(new java.awt.Dimension(7, 33));
        employ2.setPreferredSize(new java.awt.Dimension(50, 33));
        add(employ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 590, 70, 40));

        stu_ratio2.setMinimumSize(new java.awt.Dimension(7, 33));
        stu_ratio2.setPreferredSize(new java.awt.Dimension(50, 33));
        stu_ratio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stu_ratio2ActionPerformed(evt);
            }
        });
        add(stu_ratio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 650, 70, 40));

        stu_fac2.setMinimumSize(new java.awt.Dimension(7, 33));
        stu_fac2.setPreferredSize(new java.awt.Dimension(50, 33));
        add(stu_fac2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 770, 70, 40));

        academic2.setMinimumSize(new java.awt.Dimension(7, 33));
        academic2.setPreferredSize(new java.awt.Dimension(50, 33));
        add(academic2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 830, 70, 40));

        citation2.setMinimumSize(new java.awt.Dimension(7, 33));
        citation2.setPreferredSize(new java.awt.Dimension(50, 33));
        add(citation2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 530, 70, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Previous Value");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 430, -1, -1));

        jButton2.setText("Confirm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 1090, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Overall");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 980, 170, 40));

        overall1.setMinimumSize(new java.awt.Dimension(7, 33));
        overall1.setPreferredSize(new java.awt.Dimension(50, 33));
        overall1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                overall1ActionPerformed(evt);
            }
        });
        add(overall1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 980, 70, 40));

        overall2.setMinimumSize(new java.awt.Dimension(7, 33));
        overall2.setPreferredSize(new java.awt.Dimension(50, 33));
        overall2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                overall2ActionPerformed(evt);
            }
        });
        add(overall2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 980, 70, 40));

        jButton3.setText("Submit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 920, -1, -1));
    }// </editor-fold>//GEN-END:initComponents
DefaultListModel model =  new DefaultListModel();
 private void rank_box_fill(){
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","rayhan19018");
            PreparedStatement pst = con.prepareStatement("select * from university_info where University_Name = ?;");
            pst.setString(1,name.getText());
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
            curr_rank.setText(""+rs.getInt("Ranking"));
            pst = con.prepareStatement("select * from ranking_indicator where University_name = ?;");
             pst.setString(1,name.getText());
            ResultSet rs1 = pst.executeQuery();
            rs1.next();
           teach2.setText(String.valueOf(rs1.getDouble(2)));
           citation2.setText(String.valueOf(rs1.getDouble(3)));
           employ2.setText(String.valueOf(rs1.getDouble(4)));
           stu_ratio2.setText(String.valueOf(rs1.getDouble(5)));
           fac_ratio2.setText(String.valueOf(rs1.getDouble(6)));
           stu_fac2.setText(String.valueOf(rs1.getDouble(7)));
           academic2.setText(String.valueOf(rs1.getDouble(8)));
           overall2.setText(String.valueOf(rs1.getDouble(9)));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Update_Ranking.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listMouseClicked
        name.setText(list.getSelectedValue());
        list.setModel(model);
        model.removeAllElements();
        scroll.setVisible(false);
        rank_box_fill();
    }//GEN-LAST:event_listMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Admin_Ranking ob = new Admin_Ranking();
       cls.dispose();
        ob.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFocusLost
        rank_box_fill();
    }//GEN-LAST:event_nameFocusLost

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyReleased
        int count = 0;
        try {
            list.setModel(model);
            model.removeAllElements();
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","rayhan19018");
            PreparedStatement st = con.prepareStatement("select * from university_info where University_Name like ?;");
            st.setString(1,name.getText()+ "%");
            ResultSet rs = st.executeQuery();
            while(rs.next()){
                count++;
                String Item = rs.getString("University_Name");
                model.addElement(Item);
            }
            if(name.getText().trim().isEmpty())
            scroll.setVisible(false);
            else
            scroll.setVisible(true);
            if(count>9)
            count= 9;
            scroll.setSize(370,(23*count));
            list.setSize(370,(23*count));
            st.close();
            con.close();
        } catch (SQLException ex) {
            System.out.println(" ");
        }
    }//GEN-LAST:event_nameKeyReleased

    private void curr_rankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_curr_rankActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_curr_rankActionPerformed

    private void teach1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teach1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teach1ActionPerformed

    private void employ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employ1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employ1ActionPerformed

    private void stu_ratio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stu_ratio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stu_ratio1ActionPerformed

    private void citation1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_citation1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_citation1ActionPerformed

    private void academic1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_academic1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_academic1ActionPerformed

    private void teach2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teach2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teach2ActionPerformed

    private void stu_ratio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stu_ratio2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stu_ratio2ActionPerformed

    private void fac_ratio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fac_ratio2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fac_ratio2ActionPerformed
  double a,b,c,d,e,f,g,h;
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","rayhan19018");
            PreparedStatement pst1 = con.prepareStatement("update ranking_indicator set Teaching=?, Citation_per_Year=?,Employer_Reputation=?, International_Student_Ratio=?,International_Faculty_Ratio=?, Student_Faculty_Ratio=?,Academic_Ratio=?,Overall=? where University_name= ?;");
             a=Double.parseDouble(teach1.getText());
             g =Double.parseDouble(citation1.getText());
             b=Double.parseDouble(employ1.getText());
             c=  Double.parseDouble(stu_ratio1.getText());
             d= Double.parseDouble(fac_ratio1.getText());
             e= Double.parseDouble(stu_fac1.getText());
             f =Double.parseDouble(academic1.getText());
             h=(a+b+c+d+e+f+g)/7;
             DecimalFormat df = new DecimalFormat("#.00");
           
            pst1.setString(9,name.getText()); pst1.setDouble(1,a);
            pst1.setDouble(2, g);
            pst1.setDouble(3,b); pst1.setDouble(4,c);pst1.setDouble(5,d);
            pst1.setDouble(6,e);pst1.setDouble(7,f);
            pst1.setDouble(8,Double.parseDouble(df.format(h)));
            pst1.executeUpdate();
            pst1= con.prepareStatement("select * from ranking_indicator order by overall desc");
            ResultSet rs1 = pst1.executeQuery();
            pst1 = con.prepareStatement("update university_info set overall = ? where University_name = ?;");
            pst1.setDouble(1,Double.parseDouble(df.format(h)));
            pst1.setString(2,name.getText());
            pst1.executeUpdate();
            int j =1;
            while(rs1.next() && !(rs1.getString(1).equals(name.getText()))){
                j++;}
            PreparedStatement pst = con.prepareStatement("select * from university_info where Ranking >= ? and Ranking<= ? order by Ranking;");
            if(Integer.valueOf(curr_rank.getText())>j){
                pst.setInt(1,j);
                pst.setInt(2,Integer.valueOf(curr_rank.getText()));
                ResultSet rs = pst.executeQuery();
                int i = j;
                while(rs.next()){
                    PreparedStatement st = con.prepareStatement("update university_info set Ranking = ? where University_Name = ?;");
                    if(i==Integer.valueOf(curr_rank.getText()))
                    st.setInt(1,j);
                    else
                    st.setInt(1,i+1);
                    st.setString(2,rs.getString("University_Name"));
                    st.executeUpdate();
                    i++;
                    st.close();
                }
            }
            else if(Integer.valueOf(curr_rank.getText())<j){
                pst.setInt(2,j);
                pst.setInt(1,Integer.valueOf(curr_rank.getText()));
                ResultSet rs = pst.executeQuery();
                int i = Integer.valueOf(curr_rank.getText());
                while(rs.next()){
                    PreparedStatement st = con.prepareStatement("update university_info set Ranking = ? where University_Name = ?;");
                    if(i==Integer.valueOf(curr_rank.getText()))
                    st.setInt(1,j);
                    else
                    st.setInt(1,i-1);
                    st.setString(2,rs.getString("University_Name"));
                    st.executeUpdate();
                    i++;
                    st.close();
                }
            } 
            Admin_Ranking ob = new Admin_Ranking();
            cls.dispose();
            ob.setVisible(true);
            pst.close();
            JOptionPane.showMessageDialog(null,"Current Ranking of "+ name.getText() + " is "+ j);

        } catch (SQLException ex) {
            Logger.getLogger(Update_Ranking.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void overall1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_overall1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_overall1ActionPerformed

    private void overall2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_overall2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_overall2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        a=Double.parseDouble(teach1.getText());
        g =Double.parseDouble(citation1.getText());
        b=Double.parseDouble(employ1.getText());
        c=  Double.parseDouble(stu_ratio1.getText());
        d= Double.parseDouble(fac_ratio1.getText());
        e= Double.parseDouble(stu_fac1.getText());
        f =Double.parseDouble(academic1.getText());
        h=(a+b+c+d+e+f+g)/7;
        DecimalFormat df = new DecimalFormat("#.00");
        overall1.setText(df.format(h));
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField academic1;
    private javax.swing.JTextField academic2;
    private javax.swing.JTextField citation1;
    private javax.swing.JTextField citation2;
    private javax.swing.JTextField curr_rank;
    private javax.swing.JTextField employ1;
    private javax.swing.JTextField employ2;
    private javax.swing.JTextField fac_ratio1;
    private javax.swing.JTextField fac_ratio2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> list;
    private javax.swing.JTextField name;
    private javax.swing.JTextField overall1;
    private javax.swing.JTextField overall2;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JTextField stu_fac1;
    private javax.swing.JTextField stu_fac2;
    private javax.swing.JTextField stu_ratio1;
    private javax.swing.JTextField stu_ratio2;
    private javax.swing.JTextField teach1;
    private javax.swing.JTextField teach2;
    // End of variables declaration//GEN-END:variables

}
